/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package linea;

/**
 *
 * @author Hermanos
 */
public class mil50 extends javax.swing.JPanel {

    /**
     * Creates new form mil50
     */
    public mil50() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("En la década de 1950, con el objetivo de facilitar la interacción entre persona y\ncomputadora, surgieron los primeros sistemas operativos simples, como el monitor\nresidente, que cargaba programas desde cintas o tarjetas perforadas y los ejecutaba.\n\nEl primer sistema operativo reconocido fue creado en 1956 por General Motors para la\nIBM 704, encargándose básicamente de iniciar la ejecución de un programa tras la\nfinalización del anterior.");
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 560, 140));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/mil50_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 360));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
